### ISSUE TITLE
different addresses are generated using same private key

### ISSUE THREAD

**Issue by sk1122** [0xAnto/aptos-wallet-api#11]
I compared `aptos` and `aptos-wallet-api` by generating address using same private key, magically, I am getting 2 different addresses, this is a serious issue as a lot of transactions are failing, please either fix this, or mention it in the documentation

![image](https://user-images.githubusercontent.com/40713709/225537159-f464cf6b-ec6d-49c5-a03b-fd93e4e4dc46.png)

**Comment by sk1122** [comment]
PS: the latter one `0x146` is the right one generated by `aptos` library, the same is also shown on all of the wallets, the left is generated using `aptos-wallet-api`

**Comment by 0xAnto** [comment]
This error is because of passing privateKey with 0x. This issue is fixed in the latest code
